name: publish-on-pypi
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install portaudio
        run: sudo apt install -y portaudio19-dev
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.15
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
